# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  boot:
      admin:
         client:
           url: http://localhost:9999

  application:
    name: JRTP701-SSA-Web-API
server:
  port: 7071

eureka:
   client:
      service-url:
          default-zone: http://localhost:8761/eureka
#activate all the actuators
management:
      endpoint:
             env:
                 show-values: always
                 access: unrestricted
             health:
                 show-details: always
      endpoints:
            web:
              exposure:
                    include: '*'